// @generated by Diesel CLI.

diesel::table! {
    academic_progress (classroom_id, subject_id) {
        classroom_id -> Int4,
        subject_id -> Int4,
        current_progress_ratio -> Float8,
        expected_progress_ratio -> Float8,
    }
}

diesel::table! {
    classrooms (id) {
        id -> Int4,
        name -> VarChar,
        grade_level -> Int4,
    }
}

diesel::table! {
    subjects (id) {
        id -> Int4,
        name -> VarChar,
        base_periods_per_week -> Int4,
    }
}

diesel::table! {
    teacher_qualifications (teacher_id, subject_id) {
        teacher_id -> Int4,
        subject_id -> Int4,
    }
}

diesel::table! {
    teachers (id) {
        id -> Int4,
        name -> VarChar,
        max_daily_periods -> Int4,
        max_weekly_periods -> Int4,
    }
}

diesel::joinable!(academic_progress -> classrooms (classroom_id));
diesel::joinable!(academic_progress -> subjects (subject_id));
diesel::joinable!(teacher_qualifications -> subjects (subject_id));
diesel::joinable!(teacher_qualifications -> teachers (teacher_id));

diesel::allow_tables_to_appear_in_same_query!(
    academic_progress,
    classrooms,
    subjects,
    teacher_qualifications,
    teachers,
);
